spring:
  redis:
    host: localhost
    port: 6379
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  datasource:
    source:
      jdbc-url: jdbc:mysql://192.168.0.8:3307/melly_db
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
    replica1:
      jdbc-url: jdbc:mysql://192.168.0.8:3308/melly_db
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
#    replica2:
#      jdbc-url: jdbc:mysql://192.168.0.8:3309/melly_db
#      username: root
#      password: 1234
#      driver-class-name: com.mysql.cj.jdbc.Driver

app:
  auth:
    tokenExpiry: 1000000
    tokenSecret: Y21jMTF0aGFub3RoZXJjbWNzdXJmbWF0ZWNtYzExdGhhbm90aGVyY21jc3VyZm1hdGUfwegwegewfwwgwegwggsfgergtrr


cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: mellyimage
    credentials:
      access-key:
      secret-key: