spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    source:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:~/write;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialects: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
        default_batch_fetch_size: 1000
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
app:
  auth:
    tokenExpiry: 200000000
    tokenSecret: Y21jMTF0aGFub3RoZXJjbWffgkfgjwerljfgwekljfglkwejglF0ZWNtYzExdGhhbm90aGVyY21jc3VyZm1hdGUfwegwegewfwwgwegwggsfgergtrr

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      cloud-front-url:
      bucket:
    credentials:
      access-key:
      secret-key:

retry:
  count: 3
  sleep: 3000

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error