spring:
  redis:
    host: 127.0.0.1
    port: 6378
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/write;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialects: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
        default_batch_fetch_size: 1000
    generate-ddl: false
    hibernate:
      ddl-auto: create



app:
  auth:
    tokenExpiry: 1000000
    tokenSecret: Y21jMTF0aGFub3RoZXJjbWNzdXJmbWF0ZWNtYzExdGhhbm90aGVyY21jc3VyZm1hdGUfwegwegewfwwgwegwggsfgergtrr

cloud:
  aws:
    region:
      static: ap-northeast-2