client:
  oauth:
    uri:
      kakao: https://kapi.kakao.com/v2/user/me
      naver: https://openapi.naver.com/v1/nid/me
      google: https://oauth2.googleapis.com/tokeninfo
      apple: https://appleid.apple.com/auth/keys
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    source:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:~/write;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialects: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
        default_batch_fetch_size: 1000
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop

  data:
    redis:
      host: 127.0.0.1
      port: 6379
app:
  auth:
    access-expiration-time: 20000000 # 30분
    refresh-expiration-time: 1209600000 # 2주
    token-secret: Y21jMTF0aGFub3RoZXJjbWNzdXJmbWF0ZWNtYzExdGhhbm90aGVyY21jc3VyZm1hdGUfwegwegewfwwgwegwggsfgergtrr

oauth:
  resource:
    uri:
      kakao: https://kapi.kakao.com/v2/user/me
      naver: https://openapi.naver.com/v1/nid/me
      google: https://oauth2.googleapis.com/tokeninfo
      apple: https://appleid.apple.com/auth/keys

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      cloud-front-url:
      bucket:
    credentials:
      access-key:
      secret-key:

