spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    url: jdbc:mysql://${rds.host}/${rds.db}?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${rds.username}
    password: ${rds.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      format_sql: true
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    database: mysql


springdoc:
  version: v1.0.0
  api-docs:
    path: /v3/api-docs
  packages-to-scan: cmc.mellyserver
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html


app:
  auth:
    tokenExpiry: 1000000
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: mellyimagestorage
    credentials:
      access-key: ${s3.accesskey}
      secret-key: ${s3.secretkey}