version: '3'

services:
  backend:
    build: .
    ports:
      - "80:8080"
    container_name: melly-prod
    environment:
      - JVM_OPTS=-Xms1g -Xmx1g -XX:NewRatio=3 -verbosegc -server -XX:+HeapDumpOnOutOfMemoryError -javaagent:./pinpoint-agent-2.5.3/pinpoint-bootstrap-2.5.3.jar -Dpinpoint.agentId=melly01 -Dpinpoint.applicationName=melly -Dpinpoint.config=./pinpoint-agent-2.5.3/pinpoint-root.config