version: '3'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    container_name: melly-prod
    volumes:
      - /home/ec2-user/pinpoint-agent-2.5.3:/pinpoint-agent-2.5.3
    environment:
      - JVM_OPTS=-Xms1g -Xmx1g -XX:NewRatio=3 -verbosegc -server -XX:+HeapDumpOnOutOfMemoryError
      - AGENT_ID=$(ip route get 1 | awk '{print $NF;exit}')