version: '3'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    container_name: melly-prod
    environment:
      - JVM_OPTS=-Xms1g -Xmx1g -XX:NewRatio=3 -verbosegc -server -XX:+HeapDumpOnOutOfMemoryError