#server:
#  shutdown: graceful
#  tomcat:
#    accept-count: 100 # 커넥션 맺어야 하는게 8192 넘었다면, 100개 까지 대기
#    threads:
#      max: 200
#      min-spare: 10
#    max-connections: 8192 # 커넥션 8192개 맺고
spring:
  redis:
    host: localhost
    port: 6379
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  datasource:
    source:
      jdbc-url: jdbc:mysql://192.168.0.8:3307/melly_db
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
    replica1:
      jdbc-url: jdbc:mysql://192.168.0.8:3308/melly_db
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
    replica2:
      jdbc-url: jdbc:mysql://192.168.0.8:3309/melly_db
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver



#  main:
#    allow-bean-definition-overriding: true


springdoc:
  version: v1.0.0
  api-docs:
    path: /v3/api-docs
  packages-to-scan: cmc.mellyserver
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html


app:
  auth:
    tokenExpiry: 1000000
    tokenSecret: Y21jMTF0aGFub3RoZXJjbWNzdXJmbWF0ZWNtYzExdGhhbm90aGVyY21jc3VyZm1hdGUfwegwegewfwwgwegwggsfgergtrr







